// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDodModo1neiPqZew2JG-lx5se37I3FjwM',
    appId: '1:671690829131:web:b29ca1779c0cc549418cce',
    messagingSenderId: '671690829131',
    projectId: 'carcare-cebc2',
    authDomain: 'carcare-cebc2.firebaseapp.com',
    storageBucket: 'carcare-cebc2.appspot.com',
    measurementId: 'G-26V3M2G4LT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvvXqWNXl5Whk7_rroehfx5hCmCkubs_s',
    appId: '1:671690829131:android:b7777cc342bdd88f418cce',
    messagingSenderId: '671690829131',
    projectId: 'carcare-cebc2',
    storageBucket: 'carcare-cebc2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZaJYg7oMQVfyC659HVwfKi9AOHez13Tk',
    appId: '1:671690829131:ios:50b576b00a718212418cce',
    messagingSenderId: '671690829131',
    projectId: 'carcare-cebc2',
    storageBucket: 'carcare-cebc2.appspot.com',
    iosBundleId: 'com.example.carcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZaJYg7oMQVfyC659HVwfKi9AOHez13Tk',
    appId: '1:671690829131:ios:50b576b00a718212418cce',
    messagingSenderId: '671690829131',
    projectId: 'carcare-cebc2',
    storageBucket: 'carcare-cebc2.appspot.com',
    iosBundleId: 'com.example.carcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDodModo1neiPqZew2JG-lx5se37I3FjwM',
    appId: '1:671690829131:web:980e5bdd77ef87d9418cce',
    messagingSenderId: '671690829131',
    projectId: 'carcare-cebc2',
    authDomain: 'carcare-cebc2.firebaseapp.com',
    storageBucket: 'carcare-cebc2.appspot.com',
    measurementId: 'G-5ENQGD0NEB',
  );

}